apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8081